apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app
  namespace: dhaniga-ns  
spec:
  replicas: 6
  selector:
    matchLabels:
      app: fitness
  template:
    metadata:
      labels:
        app: fitness
    spec:
      containers:
      - name: fitness-container
        image: muralisocial123/fitness-app:v1.0.1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata: 
  name: fitness-app-svc 
  namespace: dhaniga-ns
spec:
  selector: 
    app: fitness
  ports: 
    - port: 3001 #It is a Service port number, we are using to expose application to the internet.
      targetPort: 5000 
      protocol: TCP
  type: NodePort   
